version: '3.8'

services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=passwordroot10011101$
     - MYSQL_DATABASE=my_database
     - MYSQL_USER=user
     - MYSQL_PASSWORD=password10011101$
     - MYSQL_HOST=localhost
      
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb-data:
